### ISSUE TITLE
Image export on Chrome leads to about:blank.

### ISSUE THREAD

**Issue by edderiofer** [sabo2/pzprv3#1]
As per the title.

To reproduce, make any new puzzle on Chrome 60.0.3112.113 (64-bit), and click on File -> Save As Image File -> Open in another window. A blank about:blank window opens instead of the correct data URI.

Exporting as new image seems to work on Firefox and Internet Explorer (though on Internet Explorer, while the image opens correctly, it still appears as though the about:blank window opens).

**Comment by sabo2** [comment]
It seems to me, Chrome's Security Policy change suffers raising another DataURL scheme window.
I fixed to comply with the change in 0cf9186e, but it needs some UI change.
I will ship in the next release.

**Comment by sabo2** [comment]
Fixed in v3.6.10
