### ISSUE TITLE
Feature request: Allow nonrectangular rooms and internal walls in Heyawake.

### ISSUE THREAD

**Issue by edderiofer** [sabo2/pzprv3#2]
As per the title; this is a variant known in the Western world as "Heyawacky". The rules are the same as Heyawake, except the "White cells must not exceed two rooms in a straight line." rule is replaced with "White cells must not cross two thick borders in a straight line."

In fact, I feel like this could be applied to other room-puzzles if it's not already done so.

**Comment by sabo2** [comment]
I removed rectangle check at sabo2/pzprjs@d4e89d8.
Please wait for the next release.

**Comment by sabo2** [comment]
Released in v3.6.10
